language: php
php:
  - 5.3
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
 - export DRUPAL=`pwd`'/drupal/'
 - export PHP=`which php`
 - curl -sS https://gist.github.com/andytruong/8ab6499fc984d05f56bb/raw/at_test.bash | bash
 - cd drupal
 - drush en --yes simpletest at_base atest_base
 - drush cc all
 - sleep 3

script: drush test-run 'AT Base'
