twig_filters:
  # ---------------------
  # Core
  # ---------------------
  render: render

  # Example: {{ 'Drupal'|t }}
  t: t

  # Example: {{ 'user/1'|url }}
  url: url

  # Example: {{ 'This is my string'|_filter_autop }}
  _filter_autop: _filter_autop

  # Example: {{ 'system:powered-by'|drupalBlock }}
  __drupalBlock: [\Drupal\at_base\Twig\Filters\Block, render]

  # Example: {{ 'user:1'|drupalEntity }}
  __drupalEntity: [\Drupal\at_base\Twig\Filters\Entity, render]

  # Examples:
  #   {{ 'viewName'|drupalView }}
  #   {{ 'viewName'|drupalView('default') }}
  #   {{ 'viewName'|drupalView('default', arg1, arg2, arg3) }}
  #   {{ 'viewName'|drupalView({template: '@at_base/templates/views_view.html.twig'}) }}
  #   {{ 'viewName'|drupalView({
  #           template: '…'
  #           , display_id: 'default'
  #           , arguments: [arg1, arg2, arg3]
  #           # ---
  #           # Pager
  #           # ---
  #             # Display a specified number of items
  #               , pager: { type: some, options: { items_per_page: 10 } }
  #             # Display all items
  #               , pager: { type: 'none' }
  #             # Paged output, full pager
  #               , pager: {
  #                 type: 'full'
  #                 options: {
  #                   , offset: 0 # The number of items to skip. For example, if this field is 3, the first 3 items will be skipped and not displayed.
  #                   , items_per_page: 10 # Items to display, The number of items to display. Enter 0 for no limit.
  #                   , total_pages: 5 # Number of pager links visible, The total number of pages. Leave empty to show all pages.
  #                   , quantity: 5 # Number of pager links visible, Specify the number of links to pages to display in the pager.
  #                   , tags: { first: '« first', previous: '« first', next: 'next ›' , last: 'last »' }
  #                 }
  #               }
  #             # Paged output, mini pager
  #               , pager: {
  #                 type: 'mini'
  #                 , options: {} # Similar to full pager
  #               }
  #           , offset: 0
  #      })
  #   }}
  __drupalView: [\Drupal\at_base\Twig\Filters\Views, render]

  # ---------------------
  # Contributed modules
  # ---------------------
  # Example: {{ variable|kpr }}
  kpr: kpr

  # Example: {{ variable|dsm }}
  dsm: dsm

  # ---------------------
  # at_base module
  # ---------------------
  # Example: {{ "%module:%id:%key"|at_config }}
  __at_config: [\Drupal\at_base\Twig\Filters\ATConfig, render]
  __cache: [\Drupal\at_base\Twig\Filters\Cache_Filter, render]
